# Generated by Django 5.0.6 on 2024-06-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, unique=True, verbose_name='Descripción')),
                ('codebar', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('brand', models.CharField(blank=True, max_length=150, null=True, verbose_name='Marca')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('weigth', models.FloatField(default=0.0, verbose_name='Peso')),
                ('is_active', models.BooleanField(default=1, verbose_name='Activo')),
                ('slug', models.SlugField()),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
