# Generated by Django 5.0.6 on 2024-06-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Und', 'Und')], default='Und', max_length=50, verbose_name='Unidad de medida'),
        ),
    ]
