# Generated by Django 5.0.6 on 2024-07-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='impuesto'),
        ),
    ]
